from __future__ import annotations

import argparse
import hashlib
import json
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import time


def _add_video_processing_to_path() -> None:
    import sys

    video_processing_dir = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(video_processing_dir))


_add_video_processing_to_path()

from inference.src.util.video_io import VideoReader, VideoWriter  # noqa: E402
from inference.src.visualization.stabilize import (  # noqa: E402
    MaskedVidStabEstimator,
    Transform,
    compute_stabilization_transforms,
    compute_stabilization_transforms_gmc,
)


@dataclass(frozen=True)
class Metrics:
    n: int
    rmse_dx: float
    rmse_dy: float
    rmse_da: float
    mae_dx: float
    mae_dy: float
    mae_da: float


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            'Run all stabilization/motion-estimation approaches from `inference.src.visualization.stabilize` '
            'and compare estimated injected transforms to the ground truth generated by '
            '`generate_jittered_video.py`.'
        )
    )
    p.add_argument('--source-video', type=str, required=True, help='Original (steady-ish) input video.')
    p.add_argument('--jittered-video', type=str, required=True, help='Synthetic jittered (cropped) video.')
    p.add_argument('--ground-truth', type=str, required=True, help='Transforms JSON from generate_jittered_video.py')

    p.add_argument(
        '--no-baseline',
        action='store_true',
        help='Compare jittered transforms directly to ground truth (skip subtracting source-video motion).',
    )
    p.add_argument(
        '--source-video-is-already-cropped',
        action='store_true',
        help='If set, do not crop source-video to match jittered-video; assume it already matches.',
    )
    p.add_argument(
        '--limit-frames',
        type=int,
        default=None,
        help='Optionally limit number of frames evaluated. Defaults to the ground-truth length.',
    )
    p.add_argument(
        '--methods',
        type=str,
        default='vidstab,gmc,masked_vidstab',
        help='Comma-separated list: vidstab,gmc,masked_vidstab',
    )
    p.add_argument(
        '--use-yolo-masks',
        action='store_true',
        help='Run YOLO detections and mask detected bboxes for methods that support it (gmc, masked_vidstab).',
    )
    p.add_argument(
        '--yolo-model-path',
        type=str,
        default=None,
        help='Override YOLO model path (defaults to `inference.src.settings.YOLO_MODEL_PATH`).',
    )
    p.add_argument(
        '--mask-margin-px',
        type=int,
        default=20,
        help='Extra padding around detected bboxes when masking keypoints.',
    )
    p.add_argument(
        '--max-bboxes-per-frame',
        type=int,
        default=10,
        help='Cap number of bboxes per frame used for masks (highest-confidence first). Use 0 for unlimited.',
    )
    p.add_argument('--gmc-downscale', type=int, default=2)
    p.add_argument('--processing-max-dim', type=float, default=float('inf'))
    p.add_argument('--temp-dir', type=str, default='tmp/stabilization_eval')
    p.add_argument('--report-out', type=str, default=None, help='Optional JSON report output path.')
    return p.parse_args()


def _load_ground_truth(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding='utf-8'))
    if 'frames' not in payload or not isinstance(payload['frames'], list):
        raise ValueError('Ground truth JSON missing `frames` list.')
    return payload


def _ground_truth_abs_by_frame(payload: dict, *, limit_frames: int | None) -> dict[int, Transform]:
    out: dict[int, Transform] = {}
    for item in payload['frames']:
        frame_idx = int(item['frame_idx'])
        if limit_frames is not None and frame_idx >= limit_frames:
            continue
        out[frame_idx] = Transform(
            dx=float(item.get('dx', 0.0)),
            dy=float(item.get('dy', 0.0)),
            da=float(item.get('da', 0.0)),
            frame_idx=frame_idx,
        )
    return out


def _abs_to_deltas(abs_by_frame: dict[int, Transform]) -> dict[int, Transform]:
    out: dict[int, Transform] = {}
    for frame_idx in sorted(abs_by_frame.keys()):
        if frame_idx == 0:
            continue
        prev = abs_by_frame.get(frame_idx - 1)
        cur = abs_by_frame.get(frame_idx)
        if prev is None or cur is None:
            continue
        out[frame_idx] = Transform(
            dx=float(cur.dx - prev.dx),
            dy=float(cur.dy - prev.dy),
            da=float(cur.da - prev.da),
            frame_idx=int(frame_idx),
        )
    return out


def _hash_for_crop(source_video: Path, crop_margin_x: int, crop_margin_y: int, limit_frames: int) -> str:
    s = f'{source_video.resolve()}|{crop_margin_x}|{crop_margin_y}|{limit_frames}'
    return hashlib.md5(s.encode('utf-8')).hexdigest()


def _ensure_cropped_video(
    source_video: Path,
    *,
    crop_margin_x: int,
    crop_margin_y: int,
    limit_frames: int,
    temp_dir: Path,
) -> Path:
    temp_dir.mkdir(parents=True, exist_ok=True)
    crop_id = _hash_for_crop(source_video, crop_margin_x, crop_margin_y, limit_frames)
    out_path = temp_dir / f'{source_video.stem}.cropped.{crop_id}.mp4'
    if out_path.exists():
        return out_path

    with VideoReader(source_video) as reader:
        props = reader.get_properties()
        out_w = int(props.width - 2 * crop_margin_x)
        out_h = int(props.height - 2 * crop_margin_y)
        if out_w <= 0 or out_h <= 0:
            raise ValueError(
                f'Crop margins too large for source size {props.width}x{props.height}: ({crop_margin_x}, {crop_margin_y})'
            )

        with VideoWriter(out_path, width=out_w, height=out_h, fps=int(props.fps), fourcc='mp4v') as writer:
            for frame_idx, frame in reader.read_frames():
                frame_idx = int(frame_idx)
                if frame_idx >= limit_frames:
                    break
                cropped = frame[
                    crop_margin_y : props.height - crop_margin_y, crop_margin_x : props.width - crop_margin_x
                ]
                writer.write_frame(cropped)

    return out_path


def _to_dict_by_frame(transforms: list[Transform]) -> dict[int, Transform]:
    return {int(t.frame_idx): t for t in transforms}


def _compute_masked_vidstab_transforms(
    video_path: Path,
    *,
    processing_max_dim: float,
    bboxes_by_frame: dict[int, list[list[int]]] | None,
    mask_margin_px: int,
) -> list[Transform]:
    estimator = MaskedVidStabEstimator(processing_max_dim=processing_max_dim)
    out: list[Transform] = []
    with VideoReader(video_path) as reader:
        for frame_idx, frame in reader.read_frames():
            excluded_bboxes = None
            if bboxes_by_frame is not None:
                excluded_bboxes = bboxes_by_frame.get(int(frame_idx), ())
            transform = estimator.apply(
                frame_idx=int(frame_idx),
                frame_bgr=frame,
                excluded_bboxes=excluded_bboxes,
                mask_margin_px=int(mask_margin_px),
            )
            if transform is not None:
                out.append(transform)
    return out


def _compute_method_transforms(
    method: str,
    video_path: Path,
    *,
    gmc_downscale: int,
    processing_max_dim: float,
    bboxes_by_frame: dict[int, list[list[int]]] | None,
    mask_margin_px: int,
) -> list[Transform]:
    if method == 'vidstab':
        return compute_stabilization_transforms(video_path)
    if method == 'gmc':
        return compute_stabilization_transforms_gmc(
            video_path,
            downscale=int(gmc_downscale),
            bboxes_by_frame=bboxes_by_frame,
        )
    if method == 'masked_vidstab':
        return _compute_masked_vidstab_transforms(
            video_path,
            processing_max_dim=float(processing_max_dim),
            bboxes_by_frame=bboxes_by_frame,
            mask_margin_px=int(mask_margin_px),
        )
    raise ValueError(f'Unknown method: {method}')


def _compute_metrics(gt: dict[int, Transform], est: dict[int, Transform]) -> Metrics:
    common = sorted(set(gt.keys()) & set(est.keys()))
    if not common:
        return Metrics(
            n=0,
            rmse_dx=float('nan'),
            rmse_dy=float('nan'),
            rmse_da=float('nan'),
            mae_dx=float('nan'),
            mae_dy=float('nan'),
            mae_da=float('nan'),
        )

    err_dx = np.array([est[i].dx - gt[i].dx for i in common], dtype=np.float64)
    err_dy = np.array([est[i].dy - gt[i].dy for i in common], dtype=np.float64)
    err_da = np.array([est[i].da - gt[i].da for i in common], dtype=np.float64)

    def rmse(x: np.ndarray) -> float:
        return float(math.sqrt(float(np.mean(x * x))))

    def mae(x: np.ndarray) -> float:
        return float(np.mean(np.abs(x)))

    return Metrics(
        n=len(common),
        rmse_dx=rmse(err_dx),
        rmse_dy=rmse(err_dy),
        rmse_da=rmse(err_da),
        mae_dx=mae(err_dx),
        mae_dy=mae(err_dy),
        mae_da=mae(err_da),
    )


def _load_yolo_bboxes_by_frame(
    video_path: Path,
    *,
    yolo_model_path: str | None,
    limit_frames: int,
    max_bboxes_per_frame: int,
) -> dict[int, list[list[int]]]:
    # Lazy import so this script can run without ultralytics unless requested.
    from inference.src.settings import YOLO_MODEL_PATH as DEFAULT_YOLO_MODEL_PATH
    from inference.src.tracking.detector import ObjectDetector

    model_path = str(DEFAULT_YOLO_MODEL_PATH) if yolo_model_path is None else str(yolo_model_path)
    detector = ObjectDetector(model_path)
    raw_detections = detector.run_detection_pass(video_path.as_posix())

    dets_by_frame: dict[int, list[tuple[float, list[int]]]] = {}
    for det in raw_detections:
        frame_idx = int(det.frame_idx)
        if frame_idx >= int(limit_frames):
            continue
        bbox = [int(det.bbox.x1), int(det.bbox.y1), int(det.bbox.x2), int(det.bbox.y2)]
        dets_by_frame.setdefault(frame_idx, []).append((float(det.confidence), bbox))

    out: dict[int, list[list[int]]] = {}
    cap = int(max_bboxes_per_frame)
    for frame_idx, items in dets_by_frame.items():
        items.sort(key=lambda t: t[0], reverse=True)
        out[frame_idx] = [bbox for _conf, bbox in (items if cap <= 0 else items[:cap])]
    return out


def main() -> int:
    args = _parse_args()

    source_video = Path(args.source_video)
    jittered_video = Path(args.jittered_video)
    gt_path = Path(args.ground_truth)

    payload = _load_ground_truth(gt_path)
    crop_margin_x = int(payload.get('crop_margin_x', 0))
    crop_margin_y = int(payload.get('crop_margin_y', 0))

    abs_by_frame = _ground_truth_abs_by_frame(payload, limit_frames=args.limit_frames)
    if not abs_by_frame:
        raise SystemExit('No ground-truth frames found (check --limit-frames).')

    limit_frames = int(args.limit_frames) if args.limit_frames is not None else (max(abs_by_frame.keys()) + 1)
    gt_deltas = _abs_to_deltas(abs_by_frame)

    temp_dir = Path(args.temp_dir)
    if args.source_video_is_already_cropped:
        source_cropped = source_video
    else:
        source_cropped = _ensure_cropped_video(
            source_video,
            crop_margin_x=crop_margin_x,
            crop_margin_y=crop_margin_y,
            limit_frames=limit_frames,
            temp_dir=temp_dir,
        )

    methods = [m.strip() for m in str(args.methods).split(',') if m.strip()]
    report: dict[str, object] = {
        'source_video': str(source_video),
        'source_video_cropped': str(source_cropped),
        'jittered_video': str(jittered_video),
        'ground_truth': str(gt_path),
        'limit_frames': int(limit_frames),
        'crop_margin_x': int(crop_margin_x),
        'crop_margin_y': int(crop_margin_y),
        'no_baseline': bool(args.no_baseline),
        'use_yolo_masks': bool(args.use_yolo_masks),
        'yolo_model_path': str(args.yolo_model_path) if args.yolo_model_path is not None else None,
        'mask_margin_px': int(args.mask_margin_px),
        'max_bboxes_per_frame': int(args.max_bboxes_per_frame),
        'methods': {},
    }

    print(f'Frames: {limit_frames} (ground-truth deltas: {len(gt_deltas)})')
    print('Method                 n     RMSE(dx,dy,da)           MAE(dx,dy,da)')

    source_bboxes_by_frame: dict[int, list[list[int]]] | None = None
    jittered_bboxes_by_frame: dict[int, list[list[int]]] | None = None
    if args.use_yolo_masks:
        print('Running YOLO detection to build per-frame masks...')
        source_bboxes_by_frame = _load_yolo_bboxes_by_frame(
            source_cropped,
            yolo_model_path=args.yolo_model_path,
            limit_frames=limit_frames,
            max_bboxes_per_frame=int(args.max_bboxes_per_frame),
        )
        jittered_bboxes_by_frame = _load_yolo_bboxes_by_frame(
            jittered_video,
            yolo_model_path=args.yolo_model_path,
            limit_frames=limit_frames,
            max_bboxes_per_frame=int(args.max_bboxes_per_frame),
        )

    for method in methods:
        start = time.time()
        src = _compute_method_transforms(
            method,
            source_cropped,
            gmc_downscale=int(args.gmc_downscale),
            processing_max_dim=float(args.processing_max_dim),
            bboxes_by_frame=source_bboxes_by_frame,
            mask_margin_px=int(args.mask_margin_px),
        )
        jit = _compute_method_transforms(
            method,
            jittered_video,
            gmc_downscale=int(args.gmc_downscale),
            processing_max_dim=float(args.processing_max_dim),
            bboxes_by_frame=jittered_bboxes_by_frame,
            mask_margin_px=int(args.mask_margin_px),
        )
        print(f'Method {method} took {time.time() - start} seconds')

        src_by_frame = _to_dict_by_frame(src)
        jit_by_frame = _to_dict_by_frame(jit)

        if args.no_baseline:
            injected_est = jit_by_frame
        else:
            injected_est = {
                frame_idx: Transform(
                    dx=float(jit_by_frame[frame_idx].dx - src_by_frame[frame_idx].dx),
                    dy=float(jit_by_frame[frame_idx].dy - src_by_frame[frame_idx].dy),
                    da=float(jit_by_frame[frame_idx].da - src_by_frame[frame_idx].da),
                    frame_idx=int(frame_idx),
                )
                for frame_idx in sorted(set(jit_by_frame.keys()) & set(src_by_frame.keys()))
            }

        metrics = _compute_metrics(gt_deltas, injected_est)
        print(
            f'{method:<20} {metrics.n:>5d}   '
            f'{metrics.rmse_dx:>8.3f} {metrics.rmse_dy:>8.3f} {metrics.rmse_da:>8.5f}   '
            f'{metrics.mae_dx:>8.3f} {metrics.mae_dy:>8.3f} {metrics.mae_da:>8.5f}'
        )

        report['methods'][method] = {
            'n': metrics.n,
            'rmse_dx': metrics.rmse_dx,
            'rmse_dy': metrics.rmse_dy,
            'rmse_da': metrics.rmse_da,
            'mae_dx': metrics.mae_dx,
            'mae_dy': metrics.mae_dy,
            'mae_da': metrics.mae_da,
        }

    if args.report_out:
        out_path = Path(args.report_out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(report, indent=2), encoding='utf-8')
        print(f'Wrote report: {out_path}')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
