export const TARGET_BBOX_HEIGHT_RATIO = 0.7
export const MIN_SCALE = 0.2
export const MAX_SCALE = 10.0
export const NEAREST_DETECTION_MAX_DELTA_FRAMES = 5
export const DETAILED_PLAYBACK_AFTER_LAST_DETECTION_SEC = 1.0
